version: '3.9'
services:
  #####################
  ## Participant 1
  postgres-edc:
    build: ./postgres
    restart: always
    ports:
      - "$POSTGRES_PORT_P1:$POSTGRES_DB_PORT"
    volumes:
      - postgres_data_p1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  connector:
    build:
      context: ./connector
      dockerfile: docker/p1/Dockerfile
    ports:
      - "$EDC_MANAGEMENT_PORT_P1:$EDC_MANAGEMENT_PORT_INTERNAL"
      - "$EDC_HTTP_PORT_P1:$EDC_HTTP_PORT_INTERNAL"
      - "$EDC_PUBLIC_PORT_P1:$EDC_PUBLIC_PORT_INTERNAL"
      - "$EDC_PROTOCOL_PORT_P1:$EDC_PROTOCOL_PORT_INTERNAL"
      - "5005:5005"
    depends_on:
      postgres-edc:
        condition: service_healthy
      identity-hub:
        condition: service_healthy
    environment:
      CONFIG_FILE: "/app/config.properties"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - connector/docker/p1/p1.env

    volumes:
      - ./connector/secrets/p1/dataspaceconnector-vault.properties:/app/dataspaceconnector-vault.properties
      - ./connector/secrets/p1/dataspaceconnector-keystore.jks:/app/dataspaceconnector-keystore.jks
    command: ["p1"]

  dataplane:
    build:
      context: ./http-dataplane
      dockerfile: Dockerfile
    ports:
      - "19192:9192"
      - "19291:9291"
      - "5002:5002"
    depends_on:
      - connector
    volumes:
      - ./http-dataplane/config.properties:/app/config.properties
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002"
    command: ["p1"]

  identity-hub:
    build:
      context: ./identity-hub
#      context: ./IdentityHub
      dockerfile: Dockerfile
    depends_on:
      postgres-edc:
        condition: service_healthy
      vault:
        condition: service_healthy
    ports:
      - "17081:7081"
      - "17083:7083"
      - "5001:5001"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5001"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8181/api/check/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "p1" ]

  vault:
    image: hashicorp/vault:${VERSION_VAULT:-latest}
    healthcheck:
      test: [ "CMD-SHELL", "vault status | grep -i 'Initialized'" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data_p1:/vault/file
    ports:
      - "18200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    command: server
    restart: always
    cap_add:
      - IPC_LOCK


#  dashboard:
#    build:
#      context: ./dashboard
#      dockerfile: Dockerfile
#    ports:
#      - "$DASHBOARD_PORT_P1:$DASHBOARD_PORT_INTERNAL"
#    depends_on:
#      - connector
#    environment:
#      - EDC_MANAGEMENT_URL=http://connector:$EDC_MANAGEMENT_PORT_INTERNAL

volumes:
  postgres_data_p1:
  vault_data_p1: