version: '3.9'
services:
  #####################
  ## Participant 2
  vault:
    image: hashicorp/vault:${VERSION_VAULT:-latest}
    healthcheck:
      test: [ "CMD-SHELL", "vault status | grep -i 'Initialized'" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data_p2:/vault/file
    ports:
      - "28200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    command: server
    restart: always
    cap_add:
      - IPC_LOCK

  postgres-edc:
    build: ./postgres
    restart: always
    ports:
      - "$POSTGRES_PORT_P2:$POSTGRES_DB_PORT"
    volumes:
      - postgres_data_p2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - connector/docker/p2/p2.env

  connector:
    build:
      context: ./connector
      dockerfile: docker/p2/Dockerfile
    ports:
      - "$EDC_MANAGEMENT_PORT_P2:$EDC_MANAGEMENT_PORT_INTERNAL"
      - "$EDC_HTTP_PORT_P2:$EDC_HTTP_PORT_INTERNAL"
      - "$EDC_PUBLIC_PORT_P2:$EDC_PUBLIC_PORT_INTERNAL"
      - "$EDC_PROTOCOL_PORT_P2:$EDC_PROTOCOL_PORT_INTERNAL"
      - "6005:6005"
    depends_on:
      postgres-edc:
        condition: service_healthy
      identity-hub:
        condition: service_healthy
    environment:
      CONFIG_FILE: "/app/config.properties"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6005"
    env_file:
      - connector/docker/p2/p2.env
    volumes:
      - ./connector/secrets/p2/dataspaceconnector-vault.properties:/app/dataspaceconnector-vault.properties
      - ./connector/secrets/p2/dataspaceconnector-keystore.jks:/app/dataspaceconnector-keystore.jks
    command: [ "p2" ]

  dataplane:
    build:
      context: ./http-dataplane
      dockerfile: Dockerfile
    ports:
      - "29192:9192"
      - "29291:9291"
    depends_on:
      - connector
    volumes:
      - ./http-dataplane/config.properties:/app/config.properties
    command: ["p2"]

  identity-hub:
    build:
      context: ./identity-hub
      dockerfile: Dockerfile
    depends_on:
      postgres-edc:
        condition: service_healthy
      vault:
        condition: service_healthy
    ports:
      - "27081:7081"
      - "27083:7083"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8181/api/check/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "p2" ]

volumes:
  postgres_data_p2:
  vault_data_p2: