version: '3.9'
services:
  identity-hub:
    build:
      context: ./identity-hub
      dockerfile: Dockerfile
    depends_on:
      postgres-edc:
        condition: service_healthy
      vault:
        condition: service_healthy
    ports:
      - "7081:7081"
      - "7083:7083"
      - "5006:5006"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8181/api/check/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [ "federator" ]
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"

  vault:
    image: hashicorp/vault:${VERSION_VAULT:-latest}
    healthcheck:
      test: [ "CMD-SHELL", "vault status | grep -i 'Initialized'" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data_fc:/vault/file
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    command: server
    restart: always
    cap_add:
      - IPC_LOCK


  postgres-edc:
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fc:
    build:
      context: ./federated-catalog
      dockerfile: Dockerfile
    depends_on:
      identity-hub:
        condition: service_healthy
    ports:
      - "9195:9195"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8181/api/check/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      CONFIG_FILE: "/app/config.properties"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"


volumes:
  vault_data_fc:
  postgres_data: